name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      
      - name: Update buildozer
        run: pip install --upgrade buildozer
      
      - name: Build APK
        run: |
          export ALLOW_ROOT=1
          yes | buildozer -v android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
